allowBuilds:
  '@firebase/util': false
  '@parcel/watcher': false
  esbuild: false
  protobufjs: false
  vue-demi: false

autoInstallPeers: true

ignoredBuiltDependencies:
  - '@firebase/util'
  - '@parcel/watcher'
  - protobufjs

onlyBuiltDependencies:
  - esbuild
  - vue-demi

shamefullyHoist: true
